# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-10 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormoperationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
